# Generated by Django 6.1.1 on 2026-09-05 15:11

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitem_order_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images/', validators=[store.validators.validate_file_size]),
        ),
    ]
